/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubes.pbo.maven.gui;

// Import class
import tubes.pbo.maven.classes.*;
import tubes.pbo.maven.database.ConnectDatabase;
import tubes.pbo.maven.classes.ButtonMenuSection;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;

/**
 *
 * @author katana
 */
public class CashierPage extends JFrame {

  /**
   * Creates new form NewJFrame
   */

  private DisplayMenuSection displayMenuSection;
  private ConnectDatabase connectDatabase;
  private ButtonMenuSection buttonMenuSection;
  private CartSection cartSection;
  private KonfirmasiMenuFrame totalHargaFrame;
  private JComboBox ActionEvent;

  public CashierPage() {
    initComponents();
    // Display Menu
    // Display Menu
    connectDatabase = new ConnectDatabase();
    displayMenuSection = new DisplayMenuSection(connectDatabase);
    displayMenuSection.displayMenu(jTable1);

    // Cart
    cartSection = new CartSection(cartTextArea, this);
    buttonMenuSection = new ButtonMenuSection(this, cartSection);

    totalHargaFrame = new KonfirmasiMenuFrame(this);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    jPanel1 = new JPanel();
    jComboBox1 = new JComboBox<>();
    jButton1 = new JButton();
    jPanel3 = new JPanel();
    titleMenu = new JTextField();
    btnSubmitMenu = new JButton();
    idMenuTextArea = new JTextField();
    jumlahMenuTextArea = new JTextField();
    jPanel4 = new JPanel();
    jTextField2 = new JTextField();
    jButton3 = new JButton();
    jTextField5 = new JTextField();
    jPanel5 = new JPanel();
    jTextField3 = new JTextField();
    jScrollPane2 = new JScrollPane();
    cartTextArea = new JTextArea();
    jPanel6 = new JPanel();
    btnAddMenu = new JButton();
    btnDeleteMenu = new JButton();
    btnKonfirmasi = new JButton();
    jScrollPane1 = new JScrollPane();
    jTable1 = new JTable();

    setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

    jComboBox1.setModel(new DefaultComboBoxModel<>(new String[] { "Menu", "Makanan", "Minuman", "Snack" }));
    jComboBox1.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        jComboBox1ActionPerformed(evt);
      }
    });

    jButton1.setText("Submit");

    GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(17, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1)
                            .addContainerGap(31, Short.MAX_VALUE))
    );

    // Button Submit Menu

    titleMenu.setText("Menu:");
    btnSubmitMenu.setText("Submit Menu");
    btnSubmitMenu.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        btnSubmitMenuActionPerformed(evt);
      }
    });

//    btnSubmitMenu.addActionListener(new java.awt.event.ActionListener() {
//      @Override
//      public void actionPerformed(java.awt.event.ActionEvent evt) {
//
//        int selectedMenuId = connectDatabase.getMenuById();
//        buttonMenuSection.handleMenuSubmit(selectedMenuId);
//      }
//    });
//
//  private void getSelectedMenuId () {
//
//    }
//    btnSubmitMenu.addActionListener(new java.awt.event.ActionListener() {
//      public void actionPerformed(java.awt.event.ActionEvent evt) {
//        btnSubmitMenuActionPerformed(evt);
//      }
//    });

    idMenuTextArea.setText("ID MENU");

    jumlahMenuTextArea.setText("JUMLAH");

    // Button Submit Menu

    GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(titleMenu, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(idMenuTextArea, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jumlahMenuTextArea, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(39, Short.MAX_VALUE))
                    .addComponent(btnSubmitMenu, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(idMenuTextArea, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titleMenu, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlahMenuTextArea, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
                            .addGap(17, 17, 17)
                            .addComponent(btnSubmitMenu, GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
    );

    jTextField2.setText("Update Harga:");
//    jTextField2.addActionListener(new java.awt.event.ActionListener() {
//      public void actionPerformed(java.awt.event.ActionEvent evt) {
//        jTextField2ActionPerformed(evt);
//      }
//    });

    jButton3.setText("Update");

    GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField5, GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                            .addContainerGap(14, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(jTextField5)))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton3, GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addContainerGap())
    );

    jTextField3.setText("CART");
//    cartTextArea.setText("Test");
    cartTextArea.setColumns(20);
    cartTextArea.setRows(5);
    jScrollPane2.setViewportView(cartTextArea);
// Cart text Area

    GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2)
                            .addContainerGap())
    );
    jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 246, GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(15, Short.MAX_VALUE))
    );
// Button Tambah  & Delete Menu:
// Button Tambah  & Delete Menu:
    btnAddMenu.setText("Tambah menu");

    btnDeleteMenu.setText("Hapus Menu");
    btnDeleteMenu.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        btnDeleteMenuActionPerformed(evt);
      }
    });

    btnAddMenu.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent evt) {
        btnAddMenuActionPerformed(evt);
      }
    });



    // Button Tambah  & Delete Menu:

    btnKonfirmasi.setText("Konfirmasi");
    btnKonfirmasi.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent evt) { btnKonfirmasi(); }
    });

    GroupLayout jPanel6Layout = new GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(btnKonfirmasi, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(btnAddMenu)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                            .addComponent(btnDeleteMenu)))
                            .addContainerGap())
    );
    jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAddMenu, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDeleteMenu, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(btnKonfirmasi, GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addContainerGap())
    );

    jTable1.setModel(new DefaultTableModel(
//            new Object [][] {
//                    {null, null, null, null},
//                    {null, null, null, null},
//                    {null, null, null, null},
//                    {null, null, null, null}
//            },
//            new String [] {
//                    "Title 1", "Title 2", "Title 3", "Title 4"
//            }
    ));
    jScrollPane1.setViewportView(jTable1);

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                            .addGap(80, 80, 80)
                                            .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                    .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addGap(69, 69, 69)
                                                            .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                            .addGap(18, 18, 18)
                                            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 848, GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(18, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE)))
                            .addContainerGap())
    );

    pack();
  }// </editor-fold>


  public JTextArea getCartTextArea() {
    return cartTextArea;
  }
  private void jComboBox1ActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
  }

//  public void titleMenu(String text) {
//    cartTextArea.setText(text);
//  }

  private void btnSubmitMenuActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
    try {
      String idMenuString = idMenuTextArea.getText();
      String jumlahMenuString = jumlahMenuTextArea.getText();

      int idMenu = Integer.parseInt(idMenuString);
      int jumlahMenu = Integer.parseInt(jumlahMenuString);
      buttonMenuSection.handleMenuSubmit(idMenu, jumlahMenu);
    } catch (NumberFormatException e) {
      // Handle the exception, for example, display an error message
      System.err.println("Invalid menu ID: " + e.getMessage());
      JOptionPane.showMessageDialog(null, "Menu ID atau quantity yang dimasukan harus angka!.");
    }
  }

private void JComboBox1ActionListener(java.awt.event.ActionEvent evt){
        private void ActionPerformed (evt){

  }
    {
      try {
        String url = "jdbc:mysql://your_database_url";
        String user = "bagus";
        String password = "123";
        Connection connection = DriverManager.getConnection(url, user, password);


        String selectedItem = jComboBox1.getSelectedItem().toString();
        String Menu = "";
        if (selectedItem.equals("one")) {
          Menu = "Makanan";
        } else if (selectedItem.equals("two")) {
          Menu = "Minuman";
        } else if (selectedItem.equals("three")) {
        } else {
          Menu = "Snack";
          // Handle the default case or throw an exception
        }

        String query = "SELECT * FROM " + Menu;
        Statement statement = connection.createStatement();
        ResultSet resultSet = statement.executeQuery(query);

        // Display data in JTextArea (assuming cartTextArea is JTextArea)
        cartTextArea.setText(""); // Clear existing text
        while (resultSet.next()) {
          String data = resultSet.getString("column_name");
          cartTextArea.append(data + "\n"); // Append data to JTextArea
        }

        resultSet.close();
        statement.close();
        connection.close();
      } catch (SQLException ex) {
        ex.printStackTrace();
        // Handle any SQL exceptions here
      }
    }

  }
//  private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
//    // TODO add your handling code here:
//  }

  private void btnDeleteMenuActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
    RemoveMenuFrame removeMenuFrame = new RemoveMenuFrame(this, cartSection);
    removeMenuFrame.setLocationRelativeTo(this);
    removeMenuFrame.setVisible(true);

  }

  private void btnAddMenuActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
    AddMenuFrame addMenuFrame = new AddMenuFrame(this, cartSection);
    addMenuFrame.setLocationRelativeTo(this);
    addMenuFrame.setVisible(true);
  }
  private void btnKonfirmasi () {
    // TODO add your handling code here:
    int idPembayaran = connectDatabase.getLastTotalHarga();

    // Set total harga pada totalHargaFrame
    totalHargaFrame.setTotalHarga(idPembayaran);

    // Tampilkan totalHargaFrame
    totalHargaFrame.setLocationRelativeTo(this);
    totalHargaFrame.setVisible(true);
  }
  public void setCartTextArea(String text) {
    cartTextArea.setText(text);
  }

//  /**
//   * @param args the command line arguments
//   */
//  public static void main(String args[]) {
//    /* Set the Nimbus look and feel */
//    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//     */
//    try {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//        if ("Nimbus".equals(info.getName())) {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//        }
//      }
//    } catch (ClassNotFoundException ex) {
//      java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (InstantiationException ex) {
//      java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (IllegalAccessException ex) {
//      java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//      java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    }
//    //</editor-fold>
//
//    /* Create and display the form */
//    java.awt.EventQueue.invokeLater(new Runnable() {
//      public void run() {
//        new NewJFrame().setVisible(true);
//      }
//    });
//  }

  // Variables declaration - do not modify
  private JButton jButton1;
  private JButton btnSubmitMenu;
  private JButton jButton3;
  private JButton btnAddMenu;
  private JButton btnDeleteMenu;
  private JButton btnKonfirmasi;
  private JComboBox<String> jComboBox1;
  private JPanel jPanel1;
  private JPanel jPanel3;
  private JPanel jPanel4;
  private JPanel jPanel5;
  private JPanel jPanel6;
  private JScrollPane jScrollPane1;
  private JScrollPane jScrollPane2;
  private JTable jTable1;
  private JTextArea cartTextArea;
  private JTextField titleMenu;
  private JTextField jTextField2;
  private JTextField jTextField3;
  private JTextField jumlahMenuTextArea;
  private JTextField jTextField5;
  private JTextField idMenuTextArea;
  // End of variables declaration
}
